print('Enter courses you take this semester')
print('Enter course 1')
course1 = input()
print('Enter course 2')
course2 = input()
print('Enter course 3')
course3 = input()
print('Enter course 4')
course4 = input()
print('Enter course 5')
course5 = input()
print('Enter course 6')
course6 = input()
print('My courses are: ')
print(course1 + ' ' + course2 + ' ' + course4 + ' ' + course5 + ' ' + course6)
